### ISSUE TITLE
Cmake/Intel compilation

### ISSUE THREAD

**Issue by tomswinburne** [tomswinburne/pafi#21]
- Issue with cmake compatibility and variable handling in `add_executable()` : only one variable permitted otherwise error
- `$LAMMPS_LIBRARIES` variable?

**Comment by Jeffery-Li0513** [comment]
thanks, I have fixed this problem. The reason is not install package in "pafi/doc/lammps_options.cmake".

**Comment by tomswinburne** [comment]
This may be due to using an older LAMMPS version- as in the pafi/doc/lammps_options.cmake, the PAFI is in the EXTRA-FIX package. 

Glad that it worked out!
